version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: umbriafestivals
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/umbriafestivals"
    volumes:
      - ./scraper:/app
    command: ["scrapy","crawl","proloco"]
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/umbriafestivals"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:8000"
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

volumes:
  postgres_data: